site_name: HStreamDB Docs

theme:
  name: "material"
  font: false
  favicon: images/favicon.png
  features:
    - instant
    - navigation.expand
  palette:
    primary: deep purple

plugins:
  - search
  - redirects:
      redirect_maps:
        'index.md': 'start/quickstart-with-docker.md'

nav:
  - Introduction:
      - Feature list
  - Getting started:
      - Quickstart with Docker: start/quickstart-with-docker.md
  - User guide: 
      - Reference:
          - SQL quick reference: guide/reference/sql-quick-reference.md
  - Command
  - Configuration
  - FAQ
  - Development:
      - Haskell style: development/haskell-style.md
      - Building from source: development/build-from-source.md

repo_url: https://github.com/hstreamdb/hstream
repo_name: hstreamdb/hstream

edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
